### ISSUE TITLE
Add required fields to create query page

### ISSUE THREAD

**Issue by mesierzega** [wmgeolab/scope#130]
We want to make it so that a user cannot submit a query unless they fill out all four fields (prompt them that they need to fill it in, like a job application)

**Comment by joegenius98** [comment]
Right now it's a standard React alert if one of the fields or more is null. Should they write their own alert? Maybe this is also a backend thing?

**Comment by joegenius98** [comment]
Status: logic functionality and an alert message are there, but they need to revise the alert message
