### ISSUE TITLE
Every result in the frontend is the same regardless of the query or the user.

### ISSUE THREAD

**Issue by devsaxena974** [wmgeolab/scope#134]
This could be a backend issue or a frontend issue so I am assigning it to both.

**Comment by mesierzega** [comment]
part of the problem right now is the frontend is just outputting the sources from the backend, not the specific results

**Comment by joegenius98** [comment]
Wait yeah. We're just using toy data right now I think. I don't think this should be labeled as a problem. I suggest turning this issue into something more like "Develop API to fetch results from GDELT". Create an additional issue: "Display fetched API results to frontend"
