### ISSUE TITLE
Map out API routes for workspaces - 

### ISSUE THREAD

**Issue by sigaloid** [wmgeolab/scope#173]
> It might be helpful for backend to have like a list of possible fetches that anything worskpace related

> for example, we probably need one endpoint to get all the queries in a given workspace

**Comment by sigaloid** [comment]
* `GET */workspaces/[id]` -> Return workspace info (name, contents, users?)
* `POST */workspaces/[id]/add` -> Send javascript array of result ID's, add to workspace.
* `POST */workspaces/[id]/remove` -> Send javascript of result ID's, remove from workspace.
* `POST */workspaces/[id]/create` -> Send javascript object with workspace name, password (?), etc. Create new workspace.

Front end, please add on to this if necessary!

**Comment by ts2002** [comment]
For rendering workspaces here is some of the information that would need to be passed back -> front:

 1. ID. integer
 2. Owner. String
 3. Name. String
 4. Tags. List of strings?

We might want to talk about what exactly we want security looks like - what does it means when a user successfully joins a workspace?

**Comment by ts2002** [comment]
For rendering individual workspaces, here is what is needed for **each** workspace:

1. Article ID (int)
2. Name (string)
3. URL (string)

**Comment by ts2002** [comment]
The skeleton fetch requests in place right now (please feel free to add to this!)

Workspaces.jsx:

1. getAllWorkspaces: Responsible for getting all workspaces a user can access -- theirs and others they have accessed.

Right now I have it passing in the user name of the current user in the header.
I am not sure if that would be needed.
Needs to return information detailed above.

2. executeView: Responsible for someone trying to "log in" to a workspace with a workspace name and password.

Right now: I have it passing in the workspace name and password.

3.executeCreate: Responsible for sending information about a workspace someone is trying to create. Guaranteed through validation to always have a name and password set by the user.

Right now: I have it passing in the workspace name and password.

indvidualWorkspacePage.jsx: Responsible for getting the information about each articles in an individual workspace.

 Right now I have it sending the workspace name and the user name (?) in the header.
Needs to return information detailed above.

**Comment by turtlu** [comment]
`GET */workspaces` -> Return all workspaces
Something I need to know is whether this returns `JSONobj.workspaces` (all workspaces) and `JSONobj.count` (number of workspaces) like in queries, or is the `JSONobj` itself the array/list of all workspaces?
