### ISSUE TITLE
How do we structure source-event-extracts?

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#35]
We need to figure out what to do when there are multiple quotes in an article referring to the same event or thing. 

Option 1) Right now we just have a flat list of extracts (ie quotes) connected to a source, with no way of knowing if the quotes are related or referring to the same thing. This would be the simplest approach, and is perhaps more in line with how a machine would do things, but I think there's a limit to how accurately one can deduplicate individual quotes in later stages without considering the broader context of the full text, so I think it would also lead to more duplicates. 

So in our last meeting we talked about wanting to have the user link these extracts together during the extraction process, because this is the only stage where we have full access and knowledge of the full source text and context. 

Option 2) I think the cleanest way to link together extracts would be to create an intermediary model called Observation or Fact or [OtherSuggestion] (with maybe a "summary" field that contains a short user-provided description, eg "riots in Williamsburg on Jan 5"), and then link to one or more Extract model instances (ie quotes) that give "proof" to that observation or fact (maybe on extract talks about when riots took place, and another extract later in the source talks about the number of people that attended). Later in the parsing module stage, the user checks out individual Observation/Fact model instances and based on the list of Extract quotes then creates Activity model instances and codes the text information in a more structured form. 

Option 3) Another way would be to have each Extract only refer to a single observation or fact, and if there's multiple quotes throughout the source just add them to the Extract's text field. This would not make it easy however to distinguish between quotes from different parts of the article and could lead to some bugs as well. 

We need to figure out which approach to use here. From previous coding projects I've been on I think it will be important to clearly differentiate between quotes and to group them together, so I would suggest and prefer option 2. The only challenge here is that this implies some human judgement during the extraction stage that will have to be somehow figured out by the automated extraction module as well (as humans it's easy, but how to make the computer figure out which quote extracts in the text refer to the same thing or event, especially in longer documents that may talk about the same events in multiple places throughout).

**Comment by micrittenden** [comment]
If I understand correctly, the intermediary module would be for Triangulating. We're grouping extracts together (triangulating info on the same event from different sources) and then sending that to the parsing phase. This is indeed how we do it in the existing workflow. Even with this approach, we can also still include the Deduplicating module (as a safety precaution) after the parsing module, so no trouble there.
My main concern is the same as yours: how does a computer replicate this module? All the methods I think of intuitively would be very computationally expensive.
Nonetheless, I believe we should include this "Triangulating" module between the "Extracting" and "Parsing" modules. My reasoning is that the output from the "Triangulating" and "Extracting" modules can be the same -- it's basically a list of text quotes. Whether that list is of length 1 (meaning either only 1 source had a passage describing the event OR the project manager chose to exclude the Triangulating module from their workflow) or 10 (meaning some combination of sources had some number of passages describing the event), the Parsing module will get a list. So, there's no harm in trying to create a Triangulating module now. Worst case scenario, it ends up as a mainly manual module for the first few iterations of SCOPE before we figure out a better way to automate. Best case, it's a total game-changer.
One more reason to include the proposed "Triangulating" module is to also include a "Deconflicting" module immediately after it. The purpose of this module would be to resolve issues of conflicting information from different sources describing the same event. There exists some literature on deconflicting text-based events data. This module could prove to be a game-changer in an age of expedient reporting, where stories are released sometimes before all the facts are triple-checked. Again, if we include a Deconflicting module, the form of the output is not a problem. For example, if we send from the Triangulating module a list of 10 extracts (quotes) to the Deconflicting module, it could output a list of 1 summarized, deconflicted quote onward to the Parsing module. How we go about Deconflicting is another problem, but we'll cross that bridge when we get there, as it isn't necessary for a bare-bones workflow.
What are your thoughts on this?

**Comment by karimbahgat** [comment]
So after reading your comments here and in #37 and #40, i’m gonna try to summarize the workflow you described to see if i understood you correctly. Sorry if this is lengthy, but i think we’re mostly there, though with some suggested clarifications/modifications. 

- So during extraction it’s simply identifying and copy-pasting relevant quote extracts. 
- Then in the triangulation module it’s triangulating quotes that belong together/refer to the same thing. 
  - My modification here though is that it should be confined to extracts from within a single source (user checks out a source), otherwise it becomes a hot mess navigating a huge list of extracts from all possible sources in order to figure out which ones are related as well as the lack of context (imagine thousands of extracts from hundreds of sources). 
  - Another issue is i’m not sure that triangulation should be optional, as i cant imagine any project where we know there’s only ever a single text reference to each event (no triangulation needed). 
  - Finally, it’s not really possible to just return a list of extracts here. There needs to be a way to store which extracts are related, and the way to do this in django would be returning some «grouped» model (eg RelatedExtracts) that links to one or more extracts, or by linking the extracts sequentially in a chain through a «previous_extract» field and returning only the initial topmost quotes. There may be other ways too. 
- Parsing then creates event structures and standardized values based on each grouped/triangulated list of extracts. 
- Deduplication would then relate event parsings from across all sources. I put this after parsing instead of before, because its much easier to compare and deduplicate structured machine readable values as opposed to unstructured text strings. This creates groups of parsed events. 
- Deconflicting would then decide on which values to keep when multiple conflicting values are given (among duplicated events). Again i put this after parsing since it makes it easier to compare and choose between structured values. This returns a single aggregated parsed event. 

On second thought i could imagine the parsing module coming immediately after extraction. I think this workflow would be even easier to automate since we’d have structured parsed events and values from the very beginning. So:

- First extract quotes. 
- Then parse, ie create the basic event structures we are interested in from each quote (eg one or multiple event objects from a single quote). 
- Then triangulate which parsed event objects from the same source are related by looking at their parsed values as well as extracts. 
- Then deduplicating in a similar way but across sources. 
- Then deconflicting contradictory parsed values. 

Let me know if i understood you right and what you think of the suggested modifications. Maybe it would help to chat in more detail over zoom at some point.

**Comment by micrittenden** [comment]
I agree with your insights. I'd be comfortable implementing either version you presented, and agree that the second option (going straight to parsing then triangulating,deduplicating,deconflicting). Though, given the logic of the modules, we'd probably swap the names for triangulating and deduplicating. Makes more sense to deduplicate within the same source and triangulate across sources.
I like where this is heading! I'm free to zoom just about whenever, just lmk when works best for you.

**Comment by micrittenden** [comment]
Ordering the modules:

Sourcing → extracting (expects source text) → deduplicating (expects extracts within sources) → parsing (expects grouped or ungrouped extracts from within sources) → triangulating (expects parsed events) → deconflicting (expects grouped parsed events) → geocoding (expects grouped deconflicted parsed or ungrouped parsed events)
