### ISSUE TITLE
Allow a source to be sent back and forth between different stages

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#36]
During extraction, a user can mark the source as finished or extracted, after which the source will no longer show up in the extraction page source list. 

- [x] Add a status choice field to Source with list of possible statuses.
- [x] In the extraction page list, only show sources that have not already been extracted. 
- [x] In the extraction checkout page, have buttons for "Cancel" which releases the source without saving anything, "Save" which saves the form and reloads the page (the source remains checked out), and "Finish" which saves and send forward to parsing stage (change status).

**Comment by lclime812** [comment]
@karimbahgat is the first sub-task for the extraction page list? Like add a column to the table showing the status? And for the other two, I think I understand the logic but am a little tripped up with HTML side. Maybe some pointers

**Comment by karimbahgat** [comment]
No, the first subtask is to add a new field to the Source model definition in models.py. More specifically add a 'status' CharField to the Source model (models.py) with list of possible status choices (https://docs.djangoproject.com/en/3.1/ref/models/fields/#choices). The logic is that a Source starts out in the list of sources for extraction (they have not yet been processed at all), and once extraction is finished it gets sent on to the parsing module, and after that it gets sent on to the next module whatever that is. We track it's progress by setting 'status' to the last completed stage of the workflow. For now it should be sufficient to have choices of 'unprocessed' (default), 'extracted', and 'parsed'. 

For the second subtask, source_list view function, simply do a filter for only those sources that have not yet been processed (hint: status='unprocessed'). Because the html is generated dynamically from the list of sources you send to the template, no need to change the html. 

For the third subtask, I think there are already some buttons in the template (source_extraction.html), just copy-paste those and adjust for each button. You'll need <a> tags and {% url %} template tags which links each button to a specific url name (defined in urls.py). For each of the buttons create new view functions in views.py and map these to urls in urls.py.

**Comment by lclime812** [comment]
I'm pretty sure I understand the first two tasks, but there is still an error. I think it might be something technical with Django that I'm not understanding. I put my code in a comment in the views.py and models.py

The third task is hard to wrap my head around the HTML from your comment. This would be good one to walk through on

**Comment by karimbahgat** [comment]
Ok, let's setup a walkthrough for this one. In the meanwhile, could you maybe have a go at #38?
