### ISSUE TITLE
Finalize the model structures of the things we want to code

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#39]
From our last meeting, it was suggested we keep it simple for now, and just use pre-determined models specific to the Grayzone project. 

- [ ] Implement the remaining model structures as outlined for the Grayzone project, eg Activity, ActivityCode, Actor, etc.

**Comment by micrittenden** [comment]
I'll update and send back when I wake up!

**Comment by karimbahgat** [comment]
Quick note on this one. We had talked earlier about renaming Activity to Event, which has yet to be done. My latest thinking is to stick to the original Activity, since Event seems too specific to only short-term instantenous type activities, while Activity seems more general and could refer to both short term events as well as more long term series of events/efforts/campaigns. At the very least it would be the easiest solution / less work for the purpose of the prototype.

**Comment by micrittenden** [comment]
Pretty sure this is done. We may need to revisit when we add the deduplication module in between extraction and parsing though.
