### ISSUE TITLE
Finalize which fields we want to store for each Source?

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#41]
One question for now: do we want to parse, clean, and store the source html from the url? Maybe for the prototype it's sufficient to only provide a url link which the user has to manually read?

**Comment by micrittenden** [comment]
I think we should get the text otherwise Dan will make us down the road anyways and it'll be a bigger pain to fix at that point. I have some simple python code to do that. We could try to adapt it to work within Django?

**Comment by karimbahgat** [comment]
Ok, so if you have a simple function that takes raw html and returns cleaned text, it would simply be a matter of running that function during whichever process populates the Source table (a separate task issue). The source date would also have to be parsed from the raw html, as long as it's recognized that accurately determinening this automatically for arbitrary source types would be difficult (I guess this could be done manually or automatically in the sourcing module, a separate task issue). 

So how about this? 
- source_html (raw html retrieved from the url, NEW FIELD)
- source_text (this would be the cleaned text, this field already exists)
- source_date (source date of publication, NEW FIELD)

This task issue would only be updating models.py, not populating the fields.
