### ISSUE TITLE
Prettify source adding, and source view

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#43]
Ie which fields do we allow selecting and viewing, and how do we want to display it.

**Comment by micrittenden** [comment]
More than just viewing, I think we need to allow for checking out and editing sources. Is there a reason we decided to not do this in the past?

**Comment by karimbahgat** [comment]
Probably because we assumed this would be predefined in a CSV for import. We probably need to have a convo about what editing/checking out a source in the sourcing stage would look like in terms of the workflow. But let's revisit this after we get the parsing module done.

**Comment by karimbahgat** [comment]
Based on 5131ba0474c1e1684dc9b855e450c7d2f033d75e, considering this closed for the purpose of the prototype.
