### ISSUE TITLE
Link the Activity model to the Extract model

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#48]
Based on our extensive conversations regarding the workflow and interaction between modules (#35 and more), make sure each Activity instance (the main unit of observation in the parsing module) can be linked to an Extract instance.

**Comment by micrittenden** [comment]
Pretty sure I've made some progress toward this. Just pushed my edits from this past weekend.

**Comment by micrittenden** [comment]
Updates to Parsing Module now have activities linked to events in the db
