### ISSUE TITLE
Maybe show all extraction sources, marking those that have been completed?

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#57]
E.g. mark the completed ones with a green completed label where the checkout button would have been. It's a bit mystifying right now where all the items go/disappear to after completion. Might make things more transparent / give a better overview, and could be a motivating factor of seeing a bunch of items completed. 

Bonus idea here is to show a percent progress bar at the top, which could be even more motivating.

**Comment by micrittenden** [comment]
I love this idea!

**Comment by micrittenden** [comment]
done
