### ISSUE TITLE
Maybe show all parsing extracts, marking those that have been completed?

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#58]
E.g. mark the completed ones with a green completed label where the checkout button would have been. It's a bit mystifying right now where all the items go/disappear to after completion. Might make things more transparent / give a better overview, and could be a motivating factor of seeing a bunch of items completed. 

Bonus idea here is to show a percent progress bar at the top, which could be even more motivating. 

At a later point we could easily add some filter or toggle to only show non-finished ones or divide it into multiple tables.

**Comment by micrittenden** [comment]
I love this idea!

**Comment by micrittenden** [comment]
done
