### ISSUE TITLE
optional date range field

### ISSUE THREAD

**Issue by micrittenden** [wmgeolab/scope#85]
in addition to the existing activity_date field (and maybe implement this for source_date as well), we should have an optional field which allows for a range-style date (e.g., a trial which lasts 7 days) or just recognize general uncertainty (we know an activity happened in 2018, but not which month/day).
There should be two fields: the first, an operator symbol; the second, a number of days.

the operators can be:    +,   -,   +/-,   ~+,   ~-,   ~+/-      where the tilde indicates uncertainty.

*this should fill the place of what we are calling "fuzzy_date"

**Comment by karimbahgat** [comment]
I'm in fact creating something similar for my geocoding platform, a pluggable django fuzzy date app that comes with a default html widget and allows for arbitrary fuzziness in many different ways. It will basically just be a textfield that follows the new [ISO 8601-2 date standard](https://www.loc.gov/standards/datetime/iso-tc154-wg5_n0039_iso_wd_8601-2_2016-02-16.pdf). We can just reuse that here when finished.
