### ISSUE TITLE
Centralize common user error handling functions and notifications so they can be imported from 'core'

### ISSUE THREAD

**Issue by karimbahgat** [wmgeolab/scope#89]
Currently, we have a set of functions in each module's views.py that checks for common user error handling functions and notifications as it relates to the model checkout system (ie any model that has a current_user attr). See #65. These functions are identical and copy-pasted to each module's views.py, which is redundant and error-prone. Instead, centralize these somewhere in the 'core' module (or maybe in a separate 'checkout' app?) and just import the functions in each module.

**Comment by micrittenden** [comment]
yup i agree 100%
